version: "3"    

volumes:
        mysql_db_data_container:


services:
        mysql_db:
                build: ./database
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment:
                        MYSQL_DATABASE: 'app'
                        MYSQL_ROOT_PASSWORD: ${DB_PASS}
                ports:
                        - 3306:3306
                expose:
                        - '3306'
                volumes:
                        - 'mysql_db_data_container:/var/lib/mysql'

        server_fast_api:
                build: .
                restart: always
                ports:
                        - 8000:8000
                network_mode: host
                entrypoint: bash -c "uvicorn main:app --reload"
